# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-19 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('language', 'language'), ('programming', 'programming'), ('else', 'else')], default='else', max_length=255, verbose_name='ジャンル'),
        ),
    ]
