# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190219_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=5000, verbose_name='本文')),
            ],
        ),
    ]
